CREATE TABLE `test_collection` (doc JSON,_id VARCHAR(32) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(doc, '$._id'))) STORED PRIMARY KEY) CHARSET utf8mb4 ENGINE=InnoDB;
CREATE TABLE `delete_collection` (doc JSON,_id VARCHAR(32) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(doc, '$._id'))) STORED PRIMARY KEY) CHARSET utf8mb4 ENGINE=InnoDB;
CREATE TABLE `test_table` (id int);
CREATE TABLE `delete_table` (id int);
CREATE TABLE update_table(
   id INT NOT NULL AUTO_INCREMENT,
   foo VARCHAR(100) NOT NULL,
   PRIMARY KEY ( id )
);
